### ISSUE TITLE
Selector naming & rule organization tip

### ISSUE THREAD

**Issue by 0xZakk** [taylorJaredD/tower_of_hanoi#4]
When you have a style rule that is shared across multiple elements, it's a good idea to pull that out into a unique class.
https://github.com/taylorJaredD/tower_of_hanoi/blob/4fff0a8ede7435e078eaeacf1766e3e9a56fb1a9/style.css#L35-L46

You could instead do something like this:

```css
.tower {
  line-height: 0.75
}

.tower-left { 
  transform: rotate(180deg); 
} 

.tower-mid { 
  transform: rotate(180deg); 
}
 
.tower-right { 
  transform: rotate(180deg); 
}
```
