### ISSUE TITLE
Rule hierarchy tip

### ISSUE THREAD

**Issue by 0xZakk** [taylorJaredD/tower_of_hanoi#5]
When you're writing a lot of CSS, you may find some selectors end up with a lot of style rules, like this `.tower` class has:

https://github.com/taylorJaredD/tower_of_hanoi/blob/4fff0a8ede7435e078eaeacf1766e3e9a56fb1a9/style.css#L24-L34

This can become difficult or tricky to maintain. There are some guidelines on how to organize your rules here that you may find helpful. [Idiomatic CSS](https://github.com/necolas/idiomatic-css) is the one I use and recommend, it has you organize style rules by type.

Under Idiomatic CSS, you organize rules by type in this order: positioning, display & box model, color, text, and other. With that, your `towers` class would look like this:

```css
.towers { 
  position: absolute; 
  z-index: 10; 
  display: flex; 
  flex-direction: row; 
  justify-content: center; 
  color: black; 
  font-family: 'Aristocrat', 'Helvetica', sans-serif; 
  font-weight: 200; 
  font-size: 200px; 
} 
```

You'll see some form of this hierarchy in the industry,
